### ISSUE TITLE
Users can view a more detailed view of one route

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/mobile#64]
In the detailed view:
- [ ] Users can see route grade
- [ ] Users can see route type (boulder, top rope, traverse, etc.)
- [ ] Users can see which rope a route is on
- [ ] Users can see route color (if applicable, traverses will not have this)
- [ ] Users can see route tags (Dyno, Crimps, Jugs, etc.)

### Upstream dependencies
- [ ] `xplat` support for Sends
- [ ] `xplat` support for Rating

### Tasks for this requirement:
- [x] #83
- [x] #84 

### Time estimate
3 days
